# Generated by Django 4.2.13 on 2024-07-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Заголовок')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='slug')),
                ('content', models.TextField(default='', verbose_name='Содержание')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='img/products', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('views_count', models.IntegerField(default=0, verbose_name='Число просмотров')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'ordering': ('name', 'created_at', 'views_count'),
                'permissions': [('set_publication', 'Установить статус публикации')],
            },
        ),
    ]
